version: "3.3"

services:
  app:
    image: traefik:1.7-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/etc/traefik/
      - ./traefik-config.toml:/etc/traefik/traefik.toml
      - ../../certs/dev.local-cert.pem:/certs/dev.local-cert.pem
      - ../../certs/dev.local-key.pem:/certs/dev.local-key.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  proxy_net:
    external: true

volumes:
  traefik-data:
